/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package di.uniba.map.b.adventure;

/**
 *
 * @author Pierdamiano
 */
public class GameJFrame extends javax.swing.JFrame {

    /**
     * Creates new form GameJFrame
     */
    public GameJFrame() {
        initComponents();
        init();
    }
    
    private void init() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerJPanel = new javax.swing.JPanel();
        roomNameJLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        movesJLabel = new javax.swing.JLabel();
        movesCounterJLabel = new javax.swing.JLabel();
        roomImageJLabel = new javax.swing.JLabel();
        textContainerJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(583, 852));

        headerJPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5)));
        headerJPanel.setPreferredSize(new java.awt.Dimension(583, 35));
        headerJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 5, 0));

        roomNameJLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        roomNameJLabel.setText("Nome stanza");
        roomNameJLabel.setMaximumSize(new java.awt.Dimension(500, 25));
        roomNameJLabel.setMinimumSize(new java.awt.Dimension(450, 25));
        roomNameJLabel.setName(""); // NOI18N
        roomNameJLabel.setPreferredSize(new java.awt.Dimension(450, 25));
        headerJPanel.add(roomNameJLabel);

        jPanel1.setPreferredSize(new java.awt.Dimension(106, 33));

        movesJLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        movesJLabel.setText("Mosse:");
        jPanel1.add(movesJLabel);

        movesCounterJLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        movesCounterJLabel.setText("1");
        movesCounterJLabel.setPreferredSize(new java.awt.Dimension(40, 25));
        jPanel1.add(movesCounterJLabel);

        headerJPanel.add(jPanel1);

        getContentPane().add(headerJPanel, java.awt.BorderLayout.NORTH);

        roomImageJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/di/uniba/map/b/adventure/img/intro.jpg"))); // NOI18N
        roomImageJLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        roomImageJLabel.setName(""); // NOI18N
        roomImageJLabel.setPreferredSize(new java.awt.Dimension(581, 300));
        getContentPane().add(roomImageJLabel, java.awt.BorderLayout.CENTER);

        textContainerJPanel.setPreferredSize(new java.awt.Dimension(583, 517));

        javax.swing.GroupLayout textContainerJPanelLayout = new javax.swing.GroupLayout(textContainerJPanel);
        textContainerJPanel.setLayout(textContainerJPanelLayout);
        textContainerJPanelLayout.setHorizontalGroup(
            textContainerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );
        textContainerJPanelLayout.setVerticalGroup(
            textContainerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        getContentPane().add(textContainerJPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel headerJPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel movesCounterJLabel;
    private javax.swing.JLabel movesJLabel;
    private javax.swing.JLabel roomImageJLabel;
    private javax.swing.JLabel roomNameJLabel;
    private javax.swing.JPanel textContainerJPanel;
    // End of variables declaration//GEN-END:variables
}
