/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package di.uniba.map.b.adventure;

import java.awt.FontFormatException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pierdamiano
 */
public class GameJFrame extends javax.swing.JFrame {

    /**
     * Creates new form GameJFrame
     */
    public GameJFrame() {
        initComponents();
        init();
    }

    private void init() {
        try {
            java.awt.Font compassFont = java.awt.Font.createFont(java.awt.Font.TRUETYPE_FONT,
                    getClass().getResourceAsStream("/di/uniba/map/b/adventure/img/LEIXO-DEMO.ttf"));
            compassNLabel.setFont(compassFont.deriveFont(java.awt.Font.PLAIN, 21f));
            compassSLabel.setFont(compassFont.deriveFont(java.awt.Font.PLAIN, 21f));
            compassELabel.setFont(compassFont.deriveFont(java.awt.Font.PLAIN, 21f));
            compassWLabel.setFont(compassFont.deriveFont(java.awt.Font.PLAIN, 21f));
            compassNELabel.setFont(compassFont.deriveFont(java.awt.Font.PLAIN, 15f));
            compassNWLabel.setFont(compassFont.deriveFont(java.awt.Font.PLAIN, 15f));
            compassSELabel.setFont(compassFont.deriveFont(java.awt.Font.PLAIN, 15f));
            compassSWLabel.setFont(compassFont.deriveFont(java.awt.Font.PLAIN, 15f));
            
        } catch (FontFormatException ex) {
            Logger.getLogger(GameJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GameJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerJPanel = new javax.swing.JPanel();
        roomNameJLabel = new javax.swing.JLabel();
        actionsJPanel = new javax.swing.JPanel();
        actionsLabel = new javax.swing.JLabel();
        movesCounterJLabel = new javax.swing.JLabel();
        roomImageJLabel = new javax.swing.JLabel();
        textContainerJPanel = new javax.swing.JPanel();
        jScrollPane1 = new ModernScrollPane(jEditorPane1);
        jEditorPane1 = new javax.swing.JEditorPane();
        jTextField1 = new javax.swing.JTextField();
        compassJPanel = new javax.swing.JPanel();
        compassNImage = new javax.swing.JLabel();
        compassWImage = new javax.swing.JLabel();
        compassCenterImage = new javax.swing.JLabel();
        compassEImage = new javax.swing.JLabel();
        compassSImage = new javax.swing.JLabel();
        compassNWJPanel = new javax.swing.JPanel();
        compassNWImage = new javax.swing.JLabel();
        compassNWLabel = new RotatedJLabel(-0.7);
        compassNEJPanel = new javax.swing.JPanel();
        compassNELabel = new RotatedJLabel(0.8);
        compassNEImage = new javax.swing.JLabel();
        compassSWJPanel = new javax.swing.JPanel();
        compassSWImage = new javax.swing.JLabel();
        compassSWLabel = new RotatedJLabel(-2.3);
        compassSEJPanel = new javax.swing.JPanel();
        compassSEImage = new javax.swing.JLabel();
        compassSELabel = new RotatedJLabel(2.4);
        compassSLabel = new javax.swing.JLabel();
        compassNLabel = new javax.swing.JLabel();
        compassWLabel = new javax.swing.JLabel();
        compassELabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(583, 852));

        headerJPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10)));
        headerJPanel.setPreferredSize(new java.awt.Dimension(583, 35));
        headerJPanel.setLayout(new java.awt.BorderLayout());

        roomNameJLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        roomNameJLabel.setText("Nome stanza");
        roomNameJLabel.setMaximumSize(new java.awt.Dimension(500, 25));
        roomNameJLabel.setMinimumSize(new java.awt.Dimension(450, 25));
        roomNameJLabel.setName(""); // NOI18N
        roomNameJLabel.setPreferredSize(new java.awt.Dimension(700, 35));
        headerJPanel.add(roomNameJLabel, java.awt.BorderLayout.WEST);

        actionsJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        actionsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        actionsLabel.setText("Azioni:");
        actionsLabel.setMaximumSize(new java.awt.Dimension(53, 35));
        actionsLabel.setMinimumSize(new java.awt.Dimension(53, 35));
        actionsLabel.setPreferredSize(new java.awt.Dimension(56, 35));
        actionsJPanel.add(actionsLabel);

        movesCounterJLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        movesCounterJLabel.setText("1");
        movesCounterJLabel.setPreferredSize(new java.awt.Dimension(40, 35));
        actionsJPanel.add(movesCounterJLabel);

        headerJPanel.add(actionsJPanel, java.awt.BorderLayout.EAST);

        getContentPane().add(headerJPanel, java.awt.BorderLayout.NORTH);

        roomImageJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/di/uniba/map/b/adventure/img/intro.jpg"))); // NOI18N
        roomImageJLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        roomImageJLabel.setName(""); // NOI18N
        roomImageJLabel.setPreferredSize(new java.awt.Dimension(581, 300));
        getContentPane().add(roomImageJLabel, java.awt.BorderLayout.CENTER);

        textContainerJPanel.setPreferredSize(new java.awt.Dimension(583, 517));
        textContainerJPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jEditorPane1.setEditable(false);
        jEditorPane1.setBackground(new java.awt.Color(60, 63, 63));
        jEditorPane1.setBorder(null);
        jEditorPane1.setContentType("text/html"); // NOI18N
        jEditorPane1.setText("<html>\r\n  <head>\r\n  </head>\r\n  <body style=\"background-color: #d6d9df;  margin: 5px;\">\r\n    <div>\r\n     <span style=\"color:red\"><strong>textArea</strong></span><br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n      test<br>\n    </div>\r\n  </body>\r\n</html>\r\n");
        jScrollPane1.setViewportView(jEditorPane1);

        textContainerJPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTextField1.setText("jTextField1");
        textContainerJPanel.add(jTextField1, java.awt.BorderLayout.SOUTH);

        getContentPane().add(textContainerJPanel, java.awt.BorderLayout.PAGE_END);

        compassJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        compassJPanel.setPreferredSize(new java.awt.Dimension(300, 300));
        compassJPanel.setLayout(new java.awt.GridBagLayout());

        compassNImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/di/uniba/map/b/adventure/img/bussola_02.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        compassJPanel.add(compassNImage, gridBagConstraints);

        compassWImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/di/uniba/map/b/adventure/img/bussola_04.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        compassJPanel.add(compassWImage, gridBagConstraints);

        compassCenterImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/di/uniba/map/b/adventure/img/bussola_05.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        compassJPanel.add(compassCenterImage, gridBagConstraints);

        compassEImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/di/uniba/map/b/adventure/img/bussola_06.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        compassJPanel.add(compassEImage, gridBagConstraints);

        compassSImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/di/uniba/map/b/adventure/img/bussola_08.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        compassJPanel.add(compassSImage, gridBagConstraints);

        compassNWJPanel.setLayout(new javax.swing.OverlayLayout(compassNWJPanel));

        compassNWImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/di/uniba/map/b/adventure/img/bussola_01.png"))); // NOI18N
        compassNWJPanel.add(compassNWImage);

        compassNWLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compassNWLabel.setText("NW");
        compassNWLabel.setMaximumSize(new java.awt.Dimension(83, 83));
        compassNWLabel.setMinimumSize(new java.awt.Dimension(83, 83));
        compassNWLabel.setPreferredSize(new java.awt.Dimension(83, 83));
        compassNWJPanel.add(compassNWLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        compassJPanel.add(compassNWJPanel, gridBagConstraints);

        compassNEJPanel.setLayout(new javax.swing.OverlayLayout(compassNEJPanel));

        compassNELabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compassNELabel.setText("NE");
        compassNELabel.setMaximumSize(new java.awt.Dimension(83, 83));
        compassNELabel.setMinimumSize(new java.awt.Dimension(83, 83));
        compassNELabel.setPreferredSize(new java.awt.Dimension(83, 83));
        compassNEJPanel.add(compassNELabel);

        compassNEImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/di/uniba/map/b/adventure/img/bussola_03.png"))); // NOI18N
        compassNEJPanel.add(compassNEImage);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        compassJPanel.add(compassNEJPanel, gridBagConstraints);

        compassSWJPanel.setLayout(new javax.swing.OverlayLayout(compassSWJPanel));

        compassSWImage.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        compassSWImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/di/uniba/map/b/adventure/img/bussola_07.png"))); // NOI18N
        compassSWImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        compassSWJPanel.add(compassSWImage);

        compassSWLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compassSWLabel.setText("SW");
        compassSWLabel.setMaximumSize(new java.awt.Dimension(83, 83));
        compassSWLabel.setMinimumSize(new java.awt.Dimension(83, 83));
        compassSWLabel.setPreferredSize(new java.awt.Dimension(83, 83));
        compassSWJPanel.add(compassSWLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        compassJPanel.add(compassSWJPanel, gridBagConstraints);

        compassSEJPanel.setLayout(new javax.swing.OverlayLayout(compassSEJPanel));

        compassSEImage.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        compassSEImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/di/uniba/map/b/adventure/img/bussola_09.png"))); // NOI18N
        compassSEImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        compassSEJPanel.add(compassSEImage);

        compassSELabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compassSELabel.setText("SE");
        compassSELabel.setMaximumSize(new java.awt.Dimension(83, 83));
        compassSELabel.setMinimumSize(new java.awt.Dimension(83, 83));
        compassSELabel.setPreferredSize(new java.awt.Dimension(83, 83));
        compassSEJPanel.add(compassSELabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        compassJPanel.add(compassSEJPanel, gridBagConstraints);

        compassSLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        compassSLabel.setText("s");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        compassJPanel.add(compassSLabel, gridBagConstraints);

        compassNLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        compassNLabel.setText("n");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        compassJPanel.add(compassNLabel, gridBagConstraints);

        compassWLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        compassWLabel.setText("w");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        compassJPanel.add(compassWLabel, gridBagConstraints);

        compassELabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        compassELabel.setText("e");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        compassJPanel.add(compassELabel, gridBagConstraints);

        getContentPane().add(compassJPanel, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionsJPanel;
    private javax.swing.JLabel actionsLabel;
    private javax.swing.JLabel compassCenterImage;
    private javax.swing.JLabel compassEImage;
    private javax.swing.JLabel compassELabel;
    private javax.swing.JPanel compassJPanel;
    private javax.swing.JLabel compassNEImage;
    private javax.swing.JPanel compassNEJPanel;
    private javax.swing.JLabel compassNELabel;
    private javax.swing.JLabel compassNImage;
    private javax.swing.JLabel compassNLabel;
    private javax.swing.JLabel compassNWImage;
    private javax.swing.JPanel compassNWJPanel;
    private javax.swing.JLabel compassNWLabel;
    private javax.swing.JLabel compassSEImage;
    private javax.swing.JPanel compassSEJPanel;
    private javax.swing.JLabel compassSELabel;
    private javax.swing.JLabel compassSImage;
    private javax.swing.JLabel compassSLabel;
    private javax.swing.JLabel compassSWImage;
    private javax.swing.JPanel compassSWJPanel;
    private javax.swing.JLabel compassSWLabel;
    private javax.swing.JLabel compassWImage;
    private javax.swing.JLabel compassWLabel;
    private javax.swing.JPanel headerJPanel;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel movesCounterJLabel;
    private javax.swing.JLabel roomImageJLabel;
    private javax.swing.JLabel roomNameJLabel;
    private javax.swing.JPanel textContainerJPanel;
    // End of variables declaration//GEN-END:variables
}
