package component.event;

public enum EventType {
    LOOK_AT, OPEN_CONTAINER, PICK_UP, PULL, AT_ROOM_ENTRANCE,
    OPEN_UNLOCKED, OPEN_LOCKED, PUSH, MOVE, INSERT, WEAR,
    EXTINGUISH, TALK_WITH, UNWEAR
}
